const { SlashCommandBuilder, PermissionsBitField } = require("discord.js");
const db = require("../database");
const { generateDashboardEmbed } = require("./dashboard");

module.exports = {
    data: new SlashCommandBuilder()
        .setName("report-today")
        .setDescription("Generate and send today's daily attendance report (Admin only)"),

    async execute(interaction) {
        // 1. Authorization check
        const isDiscordAdmin = interaction.member.permissions.has(PermissionsBitField.Flags.Administrator);
        const callerRecord = await db.getAsync("SELECT role FROM employees WHERE userId = ?", [interaction.user.id]);
        const isRegisteredAdmin = callerRecord && callerRecord.role === "Admin";

        if (!isDiscordAdmin && !isRegisteredAdmin) {
            return interaction.reply({
                content: "❌ Only administrators can generate attendance reports.",
                ephemeral: true
            });
        }

        const today = new Date().toISOString().split("T")[0];

        try {
            const reportData = await generateDashboardEmbed(interaction.guild, today);
            
            // Check if there was an informational text returned (e.g. no registered employees)
            if (reportData.content && !reportData.embeds) {
                return interaction.reply({
                    content: reportData.content,
                    ephemeral: true
                });
            }

            // Add generator detail to the embed
            if (reportData.embeds && reportData.embeds[0]) {
                reportData.embeds[0].setFooter({
                    text: `Generated by ${interaction.user.username}`,
                    iconURL: interaction.user.displayAvatarURL()
                });
            }

            // Target channel: daily report channel (ID: 1513128762903105599)
            const channelId = "1513128762903105599";
            const reportChannel = interaction.guild.channels.cache.get(channelId);

            if (reportChannel) {
                await reportChannel.send(reportData);
                await interaction.reply({
                    content: `✅ Daily report successfully generated and posted in <#${channelId}>.`,
                    ephemeral: true
                });
            } else {
                await interaction.reply({
                    content: `ℹ️ Daily report channel (<#${channelId}>) not found. Sending report directly here.`,
                    embeds: reportData.embeds
                });
            }
        } catch (error) {
            console.error("Error generating today's report:", error);
            await interaction.reply({
                content: "❌ An error occurred while generating today's attendance report.",
                ephemeral: true
            });
        }
    }
};
