const { SlashCommandBuilder, PermissionsBitField } = require("discord.js");
const db = require("../database");
const { generateReportData } = require("./report");

module.exports = {
    data: new SlashCommandBuilder()
        .setName("report-month")
        .setDescription("Generate a monthly attendance report (Admin only)")
        .addStringOption(option =>
            option
                .setName("month")
                .setDescription("Target month in YYYY-MM format (default: current month)")
                .setRequired(false)
        ),

    async execute(interaction) {
        // 1. Authorization check
        const isDiscordAdmin = interaction.member.permissions.has(PermissionsBitField.Flags.Administrator);
        const callerRecord = await db.getAsync("SELECT role FROM employees WHERE userId = ?", [interaction.user.id]);
        const isRegisteredAdmin = callerRecord && callerRecord.role === "Admin";

        if (!isDiscordAdmin && !isRegisteredAdmin) {
            return interaction.reply({
                content: "❌ Only administrators can generate attendance reports.",
                ephemeral: true
            });
        }

        const month = interaction.options.getString("month") || new Date().toISOString().substring(0, 7);

        // Validate format YYYY-MM
        if (!/^\d{4}-\d{2}$/.test(month)) {
            return interaction.reply({
                content: "❌ Invalid month format. Please use YYYY-MM (e.g., 2026-06).",
                ephemeral: true
            });
        }

        try {
            const reportData = await generateReportData(interaction.guild, month);
            if (!reportData) {
                return interaction.reply({
                    content: "⚠️ No employees registered in the database.",
                    ephemeral: true
                });
            }

            // Add generator detail to the embed
            if (reportData.embeds && reportData.embeds[0]) {
                reportData.embeds[0].setFooter({
                    text: `Generated by ${interaction.user.username}`,
                    iconURL: interaction.user.displayAvatarURL()
                });
            }

            // Target channel: monthly report channel (ID: 1512886896945266828)
            const channelId = "1512886896945266828";
            const reportChannel = interaction.guild.channels.cache.get(channelId);

            if (reportChannel) {
                await reportChannel.send(reportData);
                await interaction.reply({
                    content: `✅ Monthly report successfully generated and posted in <#${channelId}>.`,
                    ephemeral: true
                });
            } else {
                await interaction.reply({
                    content: `ℹ️ Monthly report channel (<#${channelId}>) not found. Sending report directly here.`,
                    embeds: reportData.embeds,
                    files: reportData.files
                });
            }
        } catch (error) {
            console.error("Error generating monthly report:", error);
            await interaction.reply({
                content: "❌ An error occurred while generating the monthly attendance report.",
                ephemeral: true
            });
        }
    }
};
